/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

public class Main {
    
    public static void main (String [] args) {
    	
    	Persona person = new Persona(20,"Rubén","2548598741L");
    	Persona person2 = new Persona(20,"Rubén","2548598741L");
    	
    	MiniList lista = new MiLista();
    	
    	lista.add(person);
    	lista.add(person);
    	lista.add(person);
    	lista.add("a");
    	lista.add(person2);
    	
    	
    	
    	/*if(lista.get(4)==person)
    		System.out.println("Son iguales");
    	else
    		System.out.println("Son diferentes");
    	
    	if(lista.get(4)==person2)
    		System.out.println("Son iguales");
    	else
    		System.out.println("Son diferentes");
    	
    	if(lista.contains(person2)==true)
    		System.out.println("Son iguales");
    	else
    		System.out.println("Son diferentes");
    	*/
    	
    	((MiLista) lista).lista();
    	System.out.println("---------------");
    	System.out.println(lista.contains(person));
    	lista.delete(person);
    	System.out.println("---------------");

    	((MiLista)lista).lista();
    	lista.set(person2, 1);
    	System.out.println("---------------");

    	((MiLista)lista).lista();
    	
    	System.out.println(lista.size());
    	
    	lista.clear();
    	((MiLista)lista).lista();
    	
    	System.out.println(lista.size());
    	

    	
    }
}
